version: "3.3"

services:
  myservice:
    image: nginx
    networks:
      - mynet-1 
    deploy:
      mode: global
      endpoint_mode: vip

  myclient:
    image: lb-upgrade-test-cli
    networks:
       - overlay
    deploy:
      mode: replicated
      replicas: 2

networks:
  overlay:
