version: "3.3"

services:
  service:
    image: nginx
    networks:
    - mynet
    deploy:
      mode: global
      endpoint_mode: vip

  client:
    image: lb-upgrade-test-cli
    command: ["service"]
    networks:
    - mynet
    depends_on:
    - service
    deploy:
      mode: replicated
      replicas: 2

networks:
  mynet:
    driver: overlay
